# Generated by Django 5.2.1 on 2025-06-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CrudApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("mobile_no", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[("CSE", "CSE"), ("IT", "IT"), ("ECE", "ECE")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
